// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oljjxgnlyiqivktmipjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9samp4Z25seWlxaXZrdG1pcGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDYwMjIsImV4cCI6MjA3MTQyMjAyMn0.k-vcc8_2YLZ7zerIcqRDbP_NnUUNP00bPdsazRSKpro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});